import fs from "node:fs";
import path from "node:path";
const root=process.cwd();
const eventsPath=process.env.PUBLIC_EVENTS_PATH||path.join(root,"state/public-events.json");
const outDir=process.env.SITE_OUT_DIR||path.join(root,"dist");
const siteUrl=(process.env.PUBLIC_SITE_URL||"https://code5m.github.io/tibo-reset-watch").replace(/\\/$/,"");
const channels=[["微信",process.env.WXPUSHER_SUBSCRIBE_URL||"","WxPusher Topic / 官方微信能力"],["支付宝",process.env.ALIPAY_SUBSCRIBE_URL||"","支付宝官方授权入口"],["手机短信",process.env.SMS_SUBSCRIBE_URL||"","手机号验证后接收重要 Reset"]];
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");}
function load(){try{const x=JSON.parse(fs.readFileSync(eventsPath,"utf8"));return Array.isArray(x.items)?x.items:[]}catch{return []}}
function label(x){if(x.resetKind==="completed")return "已完成";if(x.resetKind==="banked")return "Banked Reset";if(x.resetKind==="scheduled")return "已宣布时间";if(x.resetKind==="hint")return "线索";if(x.category==="project")return "项目";return "新推文"}
const events=load();
const latest=events.find(x=>x.category==="reset")||events[0]||null;
const channelHtml=channels.map(([n,u,d])=>u?'<a class="channel" href="'+esc(u)+'" target="_blank" rel="noopener"><strong>'+esc(n)+'</strong><span>'+esc(d)+'</span><b>立即订阅 →</b></a>':'<div class="channel disabled"><strong>'+esc(n)+'</strong><span>'+esc(d)+'</span><b>即将开放</b></div>').join("");
const cards=events.slice(0,30).map(x=>'<article class="event"><div><span class="badge">'+esc(label(x))+'</span><time>'+esc(x.publishedAtChina||x.publishedAt)+'</time></div><p>'+esc(x.text)+'</p><a href="'+esc(x.url)+'" target="_blank" rel="noopener">查看 Tibo 原帖 ↗</a></article>').join("");
const latestHtml=latest?'<section class="signal"><small>LATEST SIGNAL</small><h2>'+esc(label(latest))+'</h2><p>'+esc(latest.text)+'</p><strong>'+esc(latest.publishedAtChina||latest.publishedAt)+'</strong> · <a href="'+esc(latest.url)+'" target="_blank" rel="noopener">原始 X 来源 ↗</a></section>':'<section class="signal"><h2>等待第一条公开事件</h2></section>';
const css=':root{font-family:Inter,system-ui,sans-serif;background:#07111f;color:#eef4ff;line-height:1.55}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#17355f 0,transparent 28%),#07111f}a{color:#9bc7ff}.wrap{max-width:1080px;margin:auto;padding:24px}.nav{display:flex;justify-content:space-between;padding:12px 0 30px}.hero{padding:60px 0 32px}.hero h1{font-size:clamp(42px,7vw,76px);line-height:1;margin:12px 0}.hero p{font-size:20px;color:#b8c5d9;max-width:760px}.eyebrow,small{color:#79f2c0;font-weight:800;letter-spacing:.14em}.button{display:inline-block;margin-top:18px;padding:12px 18px;border-radius:12px;background:#f4f7fb;color:#07111f;text-decoration:none;font-weight:800}.signal,.channel,.event{border:1px solid #203a5f;background:#0c1b30d1;border-radius:18px}.signal{padding:26px;margin:20px 0 45px}.channels,.events{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.channel{padding:22px;text-decoration:none;min-height:155px;display:flex;flex-direction:column;gap:10px}.channel strong{font-size:22px;color:white}.channel span{color:#aebed2;flex:1}.channel b{color:#79f2c0}.disabled{opacity:.5}.section{padding:20px 0 45px}.events{grid-template-columns:1fr 1fr}.event{padding:18px}.event div{display:flex;justify-content:space-between;gap:10px}.event time{font-size:13px;color:#91a3ba}.badge{font-size:12px;background:#173155;padding:5px 9px;border-radius:99px;font-weight:800}.footer{margin-top:45px;padding:35px 0;border-top:1px solid #173153;color:#8398b2}@media(max-width:760px){.channels,.events{grid-template-columns:1fr}}';
const html='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tibo Reset Watch — Codex / ChatGPT Work Reset 中文提醒</title><meta name="description" content="监控 Tibo 的 Codex / ChatGPT Work Reset，转换北京时间并提供订阅。"><link rel="canonical" href="'+siteUrl+'/"><link rel="alternate" type="application/rss+xml" href="'+siteUrl+'/feed.xml"><meta property="og:title" content="Tibo Reset Watch"><meta property="og:description" content="Reset 原始来源、北京时间、状态分类、多渠道订阅。"><style>'+css+'</style></head><body><div class="wrap"><nav class="nav"><b>TIBO RESET WATCH</b><span><a href="#timeline">时间线</a> · <a href="feed.xml">RSS</a> · <a href="privacy.html">隐私</a></span></nav><header class="hero"><span class="eyebrow">CODEX · CHATGPT WORK · CHINA TIME</span><h1>别再错过下一次<br>额度 Reset。</h1><p>持续监控 Tibo (@thsottiaux) 的公开消息，区分已宣布、已完成、Banked Reset 与普通线索；统一转换北京时间，并保留原始 X 来源。</p><a class="button" href="#subscribe">免费订阅</a></header>'+latestHtml+'<section class="section" id="subscribe"><span class="eyebrow">SUBSCRIBE</span><h2>选择通知方式</h2><p>未配置的正式渠道显示“即将开放”，不会伪造已开通。</p><div class="channels">'+channelHtml+'</div></section><section class="section" id="timeline"><span class="eyebrow">PUBLIC TIMELINE</span><h2>Tibo 最新公开消息</h2><div class="events">'+(cards||"<article class=event><p>暂无已发布事件。</p></article>")+'</div></section><footer class="footer">非 OpenAI / X 官方产品 · <a href="privacy.html">隐私</a> · <a href="feed.json">JSON</a> · <a href="https://github.com/code5m/tibo-reset-watch">GitHub</a></footer></div></body></html>';
const privacy='<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>隐私政策 — Tibo Reset Watch</title><style>body{font:16px/1.7 system-ui;max-width:760px;margin:50px auto;padding:0 20px}</style><h1>隐私政策</h1><p>最后更新：2026-10-08</p><p>仅处理完成订阅与通知所必需的数据。用户手机号和渠道标识不得写入公开仓库或前端产物。用户应能随时暂停或退订。公开时间线来源于公开 X 帖子。本产品不是 OpenAI、X、微信或支付宝官方服务。</p><a href="./">返回首页</a>';
const rssItems=events.filter(x=>x.category==="reset").slice(0,50).map(x=>"<item><title>"+esc(label(x))+"</title><link>"+esc(x.url)+"</link><guid>"+esc(x.versionKey)+"</guid><pubDate>"+new Date(x.publishedAt).toUTCString()+"</pubDate><description>"+esc(x.text)+"</description></item>").join("");
const rss='<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Tibo Reset Watch</title><link>'+esc(siteUrl)+'</link><description>Codex / ChatGPT Work reset signals</description>'+rssItems+'</channel></rss>';
const jsonFeed=JSON.stringify({version:"https://jsonfeed.org/version/1.1",title:"Tibo Reset Watch",home_page_url:siteUrl,feed_url:siteUrl+"/feed.json",items:events.slice(0,100).map(x=>({id:x.versionKey,url:x.url,title:label(x),content_text:x.text,date_published:x.publishedAt}))},null,2)+"\\n";
fs.rmSync(outDir,{recursive:true,force:true});fs.mkdirSync(outDir,{recursive:true});
fs.writeFileSync(path.join(outDir,"index.html"),html);fs.writeFileSync(path.join(outDir,"privacy.html"),privacy);fs.writeFileSync(path.join(outDir,"feed.xml"),rss);fs.writeFileSync(path.join(outDir,"feed.json"),jsonFeed);fs.writeFileSync(path.join(outDir,"robots.txt"),"User-agent: *\\nAllow: /\\nSitemap: "+siteUrl+"/sitemap.xml\\n");fs.writeFileSync(path.join(outDir,"sitemap.xml"),'<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>'+esc(siteUrl)+'/</loc></url><url><loc>'+esc(siteUrl)+'/privacy.html</loc></url></urlset>');fs.copyFileSync(eventsPath,path.join(outDir,"events.json"));fs.writeFileSync(path.join(outDir,".nojekyll"),"");
console.log("Built public site with",events.length,"event(s)");